select H.HACKER_ID, H.NAME
from HACKERS as H
inner join SUBMISSIONS as S
on H.HACKER_ID = S.HACKER_ID
inner join CHALLENGES as C
on S.CHALLENGE_ID = C.CHALLENGE_ID
inner join DIFFICULTY as D
on C.DIFFICULTY_LEVEL = D.DIFFICULTY_LEVEL
where S.SCORE = D.SCORE and C.DIFFICULTY_LEVEL = D.DIFFICULTY_LEVEL
group by H.HACKER_ID, H.NAME
having count(S.HACKER_ID) > 1
order by count(S.HACKER_ID) desc, S.HACKER_ID asc;
